[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
description = "THAIME - Thai Input Method Editor"
authors = ["Chawit Leosrisook <chawit.leosrisook@outlook.com>"]
version = "0.6.1"
edition = "2021"
license = "MPL-2.0"
license-file = "LICENSE"
repository = "https://github.com/mimocha/thaime"
