# HawkEye license header configuration
# Run `hawkeye check` to verify all files have correct headers.
# Run `hawkeye format` to auto-add missing headers.

headerPath = "LICENSE-HEADER"

keywords = ["MPL-2.0"]

includes = [
    "crates/**/*.rs",
    "scripts/**/*.sh",
    "web/**/*.ts",
    "web/**/*.tsx",
    "web/**/*.css",
    "web/**/*.html",
]

excludes = [
    "target/**",
    "data/**",
    "web/node_modules/**",
]
