#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# ibus-engine-thaime-python - IBus engine launcher script
#
# Copyright (c) 2024 mimocha <chawit.leosrisook@outlook.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.

import sys
import os

# Add the current directory to Python path so we can import our modules
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Import and run the main application
import main

if __name__ == "__main__":
    main.main()